USE [master]
GO

/****** Object:  Database [Sample]    Script Date: 15-04-2021 14:58:44 ******/
CREATE DATABASE [Sample]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sample', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Sample.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sample_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Sample_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sample].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Sample] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Sample] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Sample] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Sample] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Sample] SET ARITHABORT OFF 
GO

ALTER DATABASE [Sample] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Sample] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Sample] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Sample] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Sample] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Sample] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Sample] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Sample] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Sample] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Sample] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Sample] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Sample] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Sample] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Sample] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Sample] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Sample] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Sample] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Sample] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Sample] SET  MULTI_USER 
GO

ALTER DATABASE [Sample] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Sample] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Sample] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Sample] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Sample] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Sample] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Sample] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Sample] SET  READ_WRITE 
GO


